# Email Configuration Setup Script
Write-Host "======================================"
Write-Host "Email Configuration Setup"
Write-Host "======================================"
Write-Host ""

# Change to the Server directory
Set-Location -Path "Server"

if (-not (Test-Path "email_config.php")) {
    Write-Host "Error: email_config.php file not found in the Server directory." -ForegroundColor Red
    Write-Host "Please make sure the file exists before running this script."
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Host "Please provide the following information:"
Write-Host "(Press Enter to keep the default value shown in brackets)"
Write-Host ""

# SMTP settings
$smtp_enabled = Read-Host "Use SMTP for sending emails? (yes/no) [yes]"
if ([string]::IsNullOrWhiteSpace($smtp_enabled)) { $smtp_enabled = "yes" }
$smtp_enabled = $smtp_enabled -eq "yes"

$smtp_host = Read-Host "SMTP Server Host [smtp.gmail.com]"
if ([string]::IsNullOrWhiteSpace($smtp_host)) { $smtp_host = "smtp.gmail.com" }

$smtp_port = Read-Host "SMTP Port [587]"
if ([string]::IsNullOrWhiteSpace($smtp_port)) { $smtp_port = "587" }
$smtp_port = [int]$smtp_port

$smtp_secure = Read-Host "SMTP Security (ssl, tls, or none) [tls]"
if ([string]::IsNullOrWhiteSpace($smtp_secure)) { $smtp_secure = "tls" }

$smtp_auth = Read-Host "Require SMTP Authentication? (yes/no) [yes]"
if ([string]::IsNullOrWhiteSpace($smtp_auth)) { $smtp_auth = "yes" }
$smtp_auth = $smtp_auth -eq "yes"

$smtp_user = Read-Host "SMTP Username (email address) [mradvision.cop@gmail.com]"
if ([string]::IsNullOrWhiteSpace($smtp_user)) { $smtp_user = "mradvision.cop@gmail.com" }

$smtp_pass = Read-Host "SMTP Password (or App Password for Gmail)" -AsSecureString
$BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($smtp_pass)
$smtp_pass = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)

# Contact form settings
$to_email = Read-Host "Recipient Email (where to send form submissions) [mradvision.cop@gmail.com]"
if ([string]::IsNullOrWhiteSpace($to_email)) { $to_email = "mradvision.cop@gmail.com" }

$from_email = Read-Host "From Email Address [noreply@adsvisionmarketing.com]"
if ([string]::IsNullOrWhiteSpace($from_email)) { $from_email = "noreply@adsvisionmarketing.com" }

$subject_prefix = Read-Host "Email Subject Prefix [New Contact Form - ]"
if ([string]::IsNullOrWhiteSpace($subject_prefix)) { $subject_prefix = "New Contact Form - " }

# Debug settings
$debug_log = Read-Host "Log email attempts? (yes/no) [yes]"
if ([string]::IsNullOrWhiteSpace($debug_log)) { $debug_log = "yes" }
$debug_log = $debug_log -eq "yes"

# Create PHP configuration file
$config = @"
<?php
// Email Configuration
// Generated by setup-email.ps1 on $(Get-Date)
return [
    // SMTP Settings
    'smtp' => [
        'enabled' => $($smtp_enabled.ToString().ToLower()),
        'host' => '$smtp_host',
        'port' => $smtp_port,
        'secure' => '$smtp_secure',
        'auth' => $($smtp_auth.ToString().ToLower()),
        'username' => '$smtp_user',
        'password' => '$smtp_pass',
    ],
    
    // Contact form email settings
    'contact_form' => [
        'to' => '$to_email',
        'from' => '$from_email',
        'subject_prefix' => '$subject_prefix',
    ],
    
    // Debug settings
    'debug' => [
        'log_email_attempts' => $($debug_log.ToString().ToLower()),
    ]
];
"@

# Write the config to the file
$config | Out-File -FilePath "email_config.php" -Encoding utf8

Write-Host ""
Write-Host "Configuration completed successfully!" -ForegroundColor Green
Write-Host "You can now use the contact form with the configured email settings."
Write-Host ""
Read-Host "Press Enter to exit"
