@echo off
echo ======================================
echo Email Configuration Setup
echo ======================================
echo.
echo This script will help you configure the email settings for your contact form.
echo.

cd Server

if not exist email_config.php (
    echo Error: email_config.php file not found in the Server directory.
    echo Please make sure the file exists before running this script.
    pause
    exit /b 1
)

echo Please provide the following information:
echo (Press Enter to keep the default value shown in brackets)
echo.

REM SMTP settings
set /p smtp_enabled="Use SMTP for sending emails? (yes/no) [yes]: "
if "%smtp_enabled%"=="" set smtp_enabled=yes

set /p smtp_host="SMTP Server Host [smtp.gmail.com]: "
if "%smtp_host%"=="" set smtp_host=smtp.gmail.com

set /p smtp_port="SMTP Port [587]: "
if "%smtp_port%"=="" set smtp_port=587

set /p smtp_secure="SMTP Security (ssl, tls, or none) [tls]: "
if "%smtp_secure%"=="" set smtp_secure=tls

set /p smtp_auth="Require SMTP Authentication? (yes/no) [yes]: "
if "%smtp_auth%"=="" set smtp_auth=yes

set /p smtp_user="SMTP Username (email address) [mradvision.cop@gmail.com]: "
if "%smtp_user%"=="" set smtp_user=mradvision.cop@gmail.com

set /p smtp_pass="SMTP Password (or App Password for Gmail): "

REM Contact form settings
set /p to_email="Recipient Email (where to send form submissions) [mradvision.cop@gmail.com]: "
if "%to_email%"=="" set to_email=mradvision.cop@gmail.com

set /p from_email="From Email Address [noreply@adsvisionmarketing.com]: "
if "%from_email%"=="" set from_email=noreply@adsvisionmarketing.com

set /p subject_prefix="Email Subject Prefix [New Contact Form - ]: "
if "%subject_prefix%"=="" set subject_prefix=New Contact Form - 

REM Debug settings
set /p debug_log="Log email attempts? (yes/no) [yes]: "
if "%debug_log%"=="" set debug_log=yes

REM Convert yes/no to true/false
if /i "%smtp_enabled%"=="yes" (
    set smtp_enabled=true
) else (
    set smtp_enabled=false
)

if /i "%smtp_auth%"=="yes" (
    set smtp_auth=true
) else (
    set smtp_auth=false
)

if /i "%debug_log%"=="yes" (
    set debug_log=true
) else (
    set debug_log=false
)

REM Create temporary PHP file for updating the config
echo ^<?php > update_config.php
echo // Generated by setup-email.bat on %date% at %time% >> update_config.php
echo. >> update_config.php
echo $config = [ >> update_config.php
echo     // SMTP Settings >> update_config.php
echo     'smtp' =^> [ >> update_config.php
echo         'enabled' =^> %smtp_enabled%, >> update_config.php
echo         'host' =^> '%smtp_host%', >> update_config.php
echo         'port' =^> %smtp_port%, >> update_config.php
echo         'secure' =^> '%smtp_secure%', >> update_config.php
echo         'auth' =^> %smtp_auth%, >> update_config.php
echo         'username' =^> '%smtp_user%', >> update_config.php
echo         'password' =^> '%smtp_pass%', >> update_config.php
echo     ], >> update_config.php
echo. >> update_config.php
echo     // Contact form email settings >> update_config.php
echo     'contact_form' =^> [ >> update_config.php
echo         'to' =^> '%to_email%', >> update_config.php
echo         'from' =^> '%from_email%', >> update_config.php
echo         'subject_prefix' =^> '%subject_prefix%', >> update_config.php
echo     ], >> update_config.php
echo. >> update_config.php
echo     // Debug settings >> update_config.php
echo     'debug' =^> [ >> update_config.php
echo         'log_email_attempts' =^> %debug_log%, >> update_config.php
echo     ] >> update_config.php
echo ]; >> update_config.php
echo. >> update_config.php
echo file_put_contents('email_config.php', '<?php' . PHP_EOL . '// Email Configuration' . PHP_EOL . 'return ' . var_export($config, true) . ';'); >> update_config.php
echo echo 'Configuration updated successfully!'; >> update_config.php
echo ^?^> >> update_config.php

REM Run the PHP script to update the config
php update_config.php
if %errorlevel% neq 0 (
    echo Failed to update configuration.
    echo Make sure PHP is installed and available in your PATH.
    del update_config.php
    pause
    exit /b 1
)

REM Clean up
del update_config.php

echo.
echo Configuration completed successfully!
echo You can now use the contact form with the configured email settings.
echo.
pause
